menu:
  首页: /
  归档: /archives
  关于: /about

excerpt_link: 阅读全文
archive_yearly: true

widgets:
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll

blogrolls:
  - Heroic Yang's Blog: http://heroicyang.com/

fancybox: true

duoshuo_shortname: zhaiyz

google_analytics:
rss:
